export const profile = {
  name: "Douglas Michael Soule",
  role: "Freelance Full Stack Engineer",
  location: "Salt Lake City, Utah",
  email: "souledouglas061@gmail.com",
  linkedin: "https://www.linkedin.com/in/souleman13",
  github: "https://github.com/soulemandev",
  summary:
    "Full stack engineer and business owner with 8+ years building robust, scalable web solutions. Recent work spans testing JavaScript generated by AI chatbots and building a data-unification platform that links a gamer's stats across every platform, device, and service in one place.",
  summary2:
    "At Astronauts and Aliens Technology Consulting, I partner directly with clients to grow their digital footprint and improve SEO. Fluency across the JavaScript ecosystem and major cloud platforms is what makes that possible, project after project.",
  topSkills: ["Artificial Intelligence (AI)", "React Native", "Mobile Application Development"],
  certifications: ["Google AI Essentials"],
};

export type ExperienceEntry = {
  company: string;
  title: string;
  dates: string;
  location: string;
  bullets: string[];
};

export const experience: ExperienceEntry[] = [
  {
    company: "Astronauts and Aliens Technology Consulting",
    title: "Full Stack Engineer & Owner",
    dates: "Nov 2023 — Present",
    location: "Salt Lake City, Utah",
    bullets: [
      "Developed SEO strategies and improved web footprint for small businesses through freelance web development projects.",
      "Gathered project requirements directly with clients to enhance their online presence and drive business growth.",
      "Ran AI input/output testing on JavaScript generated by an AI engine, focused on React and Angular frontend output.",
      "Built project demos and proofs of concept using JavaScript, React, and serverless Lambda APIs (AWS Lambda, Azure Functions).",
      "Migrated an e-commerce site from BigCommerce to Shopify, including customers, products, coupons, and blog posts — with redirects for 470 products to retain SEO equity.",
    ],
  },
  {
    company: "Modere",
    title: "Full Stack Developer",
    dates: "Sep 2022 — Aug 2023",
    location: "Salt Lake City, Utah",
    bullets: [
      "Developed and maintained a cross-platform, cross-browser e-commerce application live in 20 countries and 7 languages.",
      "Integrated RESTful APIs to connect front-end interfaces with back-end systems and databases.",
      "Maintained an Angular frontend and Mulesoft functions written in .NET Core.",
      "Helped migrate the frontend codebase from Angular 8 to React + Next.js.",
    ],
  },
  {
    company: "Software Technology Group",
    title: "Full Stack Developer",
    dates: "Aug 2021 — Sep 2022",
    location: "Salt Lake City, Utah",
    bullets: [
      "Developed and maintained a cross-platform, cross-browser e-commerce application live in 20 countries and 7 languages.",
      "Collaborated with cross-functional teams to design scalable solutions and a strong user experience.",
      "Maintained an Angular frontend and Mulesoft functions written in .NET Core.",
      "Helped migrate the frontend codebase from Angular 8 to React + Next.js.",
    ],
  },
  {
    company: "Astronauts and Aliens Technology Consulting",
    title: "Full Stack Developer & Owner",
    dates: "May 2020 — Apr 2021",
    location: "Salt Lake City Metro Area",
    bullets: [
      "Delivered IT services, automated backups, and maintained servers for ACCI Services.",
      "Built a wholesale shipping-label API platform using React, JavaScript, and AWS for GOA.",
      "Maintained an API selling wholesale shipping labels worldwide for E1, using JavaScript, PHP, and AWS.",
    ],
  },
  {
    company: "Deltatre",
    title: "Full Stack Developer",
    dates: "Dec 2018 — May 2020",
    location: "Salt Lake City, Utah",
    bullets: [
      "Collaborated with international teams to deliver flagship products including GolfTV and NFL Game Pass.",
      "Integrated multiple languages, currencies, and platforms for a seamless worldwide user experience.",
      "Contributed to driving user engagement across both products.",
    ],
  },
  {
    company: "HNK Ideas",
    title: "Full Stack Developer",
    dates: "Sep 2017 — Dec 2018",
    location: "Greater Salt Lake City Area",
    bullets: [
      "Built a Go adapter pattern for data pipelines spanning cloud SQL and NoSQL databases at Big Squid.",
      "Created a supervisor dashboard for 911 call-center performance monitoring using Angular 6 and ASP.NET at Priority Dispatch.",
      "Led a 3-person team building a functional demo for Blitz, a startup utility-bill-payment platform, using React and GraphQL.",
    ],
  },
  {
    company: "Helio Training",
    title: "Mentor",
    dates: "Jan 2018 — May 2018",
    location: "Draper, Utah",
    bullets: [
      "Created teaching aids and assignments to strengthen the learning experience for instructors.",
      "Resolved coding bugs promptly to keep students moving through lessons.",
      "Guided students through documentation and project architecture, from HTML basics to deployed full-stack MERN apps.",
    ],
  },
];

export const education = [
  {
    school: "Southern Utah University",
    program: "Computer and Information Sciences, General",
    dates: "Aug 2013 — May 2016",
  },
  {
    school: "Helio Training",
    program: "Certificate of Proficiency and Completion, Full-Stack Full Time Web Development",
    dates: "2017",
  },
  {
    school: "Salt Lake Community College",
    program: "Computer Science",
    dates: "2015 — 2016",
  },
];

export type Project = {
  name: string;
  dates: string;
  description: string;
  tags: string[];
  status?: string;
};

export const featuredProjects: Project[] = [
  {
    name: "Uber Driver Support Assistant",
    dates: "Mar 2025",
    description:
      "Mobile app that captures screen recordings and evidence for Uber driver support tickets so fees are properly awarded to drivers. Includes an AI agent that handles conversations with Uber support and submits claim evidence on the driver's behalf.",
    tags: ["React Native", "AI Agents", "Mobile"],
  },
  {
    name: "Project PSI",
    dates: "Aug 2024 — Present",
    description:
      "Subscription app linking a gamer's stats, accolades, and history across every platform, device, and service into one persona. Currently building the MVP; codebase owned by Douglas and available as a live example on request.",
    tags: ["Full Stack", "Product", "Owner"],
    status: "In development · repo private",
  },
  {
    name: "Skin Actives — BigCommerce → Shopify",
    dates: "Jan 2025 — Apr 2025",
    description:
      "Migrated a full e-commerce catalog off BigCommerce onto Shopify: customers, orders, coupons and discounts, and blog content. Shipped redirects for 470 products to retain SEO equity from the previous domain.",
    tags: ["E-commerce", "Shopify", "SEO"],
  },
  {
    name: "Modere Global E-Commerce Platform",
    dates: "Aug 2021 — Aug 2023",
    description:
      "Primary storefront for Modere.com, serving 20 countries in 7 languages. Migrated the frontend from Angular 8 to React and Next.js as part of the platform's long-term modernization.",
    tags: ["Angular", "React", "Next.js"],
  },
  {
    name: "GolfTV",
    dates: "Dec 2018 — May 2020",
    description:
      "Streaming home for all golf content worldwide, owned by the PGA Tour, covering every PGA and LPGA Tour. Live in over 30 countries and 8 languages during Douglas's time on the project.",
    tags: ["Streaming", "i18n", "Scale"],
  },
  {
    name: "NFL Game Pass (now NFL+)",
    dates: "Mar 2019 — Jul 2019",
    description:
      "Online streaming home for NFL content, originally focused on EU market delivery but available globally — the direct predecessor of today's NFL+.",
    tags: ["Streaming", "Sports Tech"],
  },
];

export const additionalProjects: Project[] = [
  {
    name: "NFL 100th Anniversary Mini-site",
    dates: "Jun 2019 — Jul 2019",
    description: "Small single-page application promoting the NFL's 100th anniversary activities.",
    tags: ["SPA"],
  },
  {
    name: "NFL Team Homepages",
    dates: "Jun 2019 — Jul 2019",
    description:
      "One of three shared site formats selected at build time per team, content-managed by the Delta Forge CMS and deployed per domain. Douglas handled pre-season performance maintenance.",
    tags: ["CMS", "Performance"],
  },
  {
    name: "Gamer.id",
    dates: "Nov 2018 — May 2019",
    description: "The original v1 of Project PSI — combining stats from disconnected gaming sources in one place.",
    tags: ["v1", "Gaming"],
  },
  {
    name: "Big Squid",
    dates: "Jul 2018 — Oct 2018",
    description: "Adapter pattern combining NoSQL, SQL, and graph database outputs into unified data pipelines.",
    tags: ["Data Pipelines", "Go"],
  },
  {
    name: "Priority Dispatch",
    dates: "Feb 2018 — Jul 2018",
    description:
      "6-month contract on a 4-person team building a dashboard for supervisors of 911 call operators to monitor performance and compliance.",
    tags: ["Angular", "ASP.NET"],
  },
  {
    name: "Blitz",
    dates: "Oct 2017 — Dec 2017",
    description:
      "Subscription and monthly-payment tracker in the spirit of today's Rocket Money. Led a 3-person team to build a funding demo for the founder.",
    tags: ["React", "GraphQL"],
  },
  {
    name: "Bar-App",
    dates: "Jun 2017 — Oct 2017",
    description:
      "Capstone project for Helio Training, competing against 3rd- and 4th-year university teams.",
    tags: ["Capstone"],
    status: "Best in Show · Staff Pick — Neumont University Student Showcase, Fall 2017",
  },
];
